---
# MagicLink ConfigMap with service configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "magiclink.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "magiclink.labels" . | nindent 4 }}
data:
  # Use RS256 or HS256 signing
  SIGNING_ALG: {{ .Values.config.signingAlg | quote }}
  # Cookie name for token storage
  COOKIE_NAME: {{ .Values.config.cookieName | quote }}
  # Query parameter name for token
  TOKEN_PARAM: {{ .Values.config.tokenParam | quote }}
  # JWT issuer claim
  ISSUER: {{ .Values.config.issuer | quote }}
  # Log level
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  # Automatic key rotation
  AUTO_ROTATE_KEYS: {{ .Values.config.autoRotateKeys | quote }}
  # Service addresses
  HTTP_ADDR: {{ .Values.config.httpAddr | quote }}
  # Key paths
  KEY_PATHS: {{ .Values.config.keyPaths | quote }}
  {{- if eq .Values.config.signingAlg "HS256" }}
  # HMAC secret for HS256 mode
  HMAC_SECRET: {{ .Values.config.hmacSecret | quote }}
  {{- end }}
  # Default token TTL
  DEFAULT_TTL: {{ .Values.config.defaultTTL | quote }}