apiVersion: v2
name: magiclink
description: A stateless, JWT-based authentication service for Kubernetes
type: application
version: 0.1.0
appVersion: "latest"
home: https://github.com/robertlestak/magiclink
sources:
  - https://github.com/robertlestak/magiclink
maintainers:
  - name: MagicLink Maintainers
keywords:
  - authentication
  - jwt
  - token
  - authorization
  - istio
dependencies:
  - name: cert-manager
    version: "^1.0.0"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
    tags:
      - cert-manager